---
title: "EDA"
format: html
---

# Exploratory Data Analysis

```{r echo=FALSE, message=FALSE, warning=FALSE}
data <- readRDS("data/eda_data.rds")
c(
nrow(data[which(data$TWF + data$HDF + data$PWF + data$OSF + data$RNF >= 2),]),
nrow(data[which(data$TWF + data$HDF + data$PWF + data$OSF + data$RNF >= 3),]),
nrow(data[which(data$TWF + data$HDF + data$PWF + data$OSF + data$RNF >= 4),]),
nrow(data[which(data$TWF + data$HDF + data$PWF + data$OSF + data$RNF >= 5),]))




failures <- data.frame(failure_type=c("TWF","HWD","PWF","OSF","RNF"),sum=c(sum(data$TWF),sum(data$HDF),sum(data$PWF),sum(data$OSF),sum(data$RNF)))

failures$failure_type <- as.factor(failures$failure_type)

# sum(failures$sum)-sum(as.numeric(data$Machine_failure)-1)
# 
# data[which(data$Machine_failure==0 & (data$TWF + data$HDF + data$PWF + data$OSF + data$RNF != 0)),]
# 
# data[which(data$RNF==1),]
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(grid)
load("data/model_data.rda")

model_data %>%
  mutate(Machine_failure=ifelse(Machine_failure==1,"Yes","No")) %>%
  ggplot(aes(y=Machine_failure,x=Tool_wear,fill=Machine_failure))+
    geom_boxplot(show.legend = FALSE)+
    labs(x="Tool wear[min]", y="Failure occured")+
    scale_fill_manual(values = c("blue","red"))+
    theme_classic(base_size = 15)

text_1 <- textGrob("Tool\nWear\nFailure", gp=gpar(fontsize=13))
text_2 <- textGrob("Heat\ndissipation\nFailure", gp=gpar(fontsize=13))
text_3 <- textGrob("Power\nFailure", gp=gpar(fontsize=13))
text_4 <- textGrob("Overstrain\nFailure", gp=gpar(fontsize=13))
text_5 <- textGrob("Random\nFailure", gp=gpar(fontsize=13))


f1 <- failures %>%
  ggplot(aes(x=reorder(failure_type, -sum),y=sum,fill=failure_type))+
  geom_col(show.legend = F)+
  geom_hline(yintercept = seq(30,120,by=30), linetype = "dashed", color = "black", alpha = 0.4, size=0.3)+
  scale_y_continuous(breaks = seq(30,120,by=30))+
  labs(x="Failure Type",y="Number of occurances",title="Occurrences of failure types")+
  scale_fill_brewer(palette = "Dark2")+
  theme_classic(base_size = 15)+
  annotation_custom(text_2,xmin=1,xmax=1,ymin=-0.07,ymax=27)+ 
  annotation_custom(text_4,xmin=2,xmax=2,ymin=-0.07,ymax=17)+
  annotation_custom(text_3,xmin=3,xmax=3,ymin=-0.07,ymax=17)+ 
  annotation_custom(text_1,xmin=4,xmax=4,ymin=-0.07,ymax=27)+
  annotation_custom(text_5,xmin=5,xmax=5,ymin=-0.07,ymax=17)+
  coord_cartesian(clip = "off")

save(f1,file = "plots/eda_f.rda")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggmosaic)
library(ggcorrplot)

ggplot(na.omit(model_data))+
  geom_mosaic(aes(x = product(Machine_failure), fill=Type), show.legend = F)+
  labs(title = "Zależność usterk od jakościo produktu")+
  theme_mosaic()+
  theme(plot.title = element_text(hjust = 0.5,size=22))
##jedyny mozaikowy który ma chyba sens, ale może lepiej boxplotem

model.matrix(~0+., data=model_data[,-c(1:2)]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(gridExtra)

p1 <- data %>% 
  mutate(Machine_failure=ifelse(Machine_failure==1,"yes","no")) %>% 
  ggplot(aes(x=Air_temperature,fill=Machine_failure,legend=F)) +
  geom_histogram(colour="black")+
  facet_wrap(~Machine_failure,scales="free_y",labeller = label_both)+
  scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Air temperature", y = "Count")
p2 <- data %>% 
  mutate(Machine_failure=ifelse(Machine_failure==1,"yes","no")) %>% 
  ggplot(aes(x=Process_temperature,fill=Machine_failure,legend=F)) +
  geom_histogram(colour="black")+
  facet_wrap(~Machine_failure,scales="free_y",labeller = label_both)+
  scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Process temperature", y = "Count")
p3 <- data %>% 
  mutate(Machine_failure=ifelse(Machine_failure==1,"yes","no")) %>% 
  ggplot(aes(x=Rotational_speed,fill=Machine_failure,legend=F)) +
  geom_histogram(colour="black")+
  facet_wrap(~Machine_failure,scales="free_y",labeller = label_both)+
  scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Rotational speed", y = "Count")
p4 <- data %>% 
  mutate(Machine_failure=ifelse(Machine_failure==1,"yes","no")) %>% 
  ggplot(aes(x=Torque,fill=Machine_failure,legend=F)) +
  geom_histogram(colour="black")+
  facet_wrap(~Machine_failure,scales="free_y",labeller = label_both)+
  scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Torque", y = "Count")
p5 <- data %>% 
  mutate(Machine_failure=ifelse(Machine_failure==1,"yes","no")) %>% 
  ggplot(aes(x=Tool_wear,fill=Machine_failure,legend=F)) +
  geom_histogram(colour="black")+
  facet_wrap(~Machine_failure,scales="free_y",labeller = label_both)+
  scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Tool Wear", y = "Count")
p6 <- data %>% 
  ggplot(aes(x=Machine_failure,fill=Machine_failure)) +
  geom_bar(colour="black")+
    scale_fill_manual(values=c("blue","red"))+
  theme(legend.position="none")+
  labs(x="Machine failure", y = "Count")

save(p1,p2,p3,p4,p5,p6,file = "plots/eda_p.rda")

grid.arrange(p1,p2,ncol=1)
grid.arrange(p3,p4,ncol=1)
grid.arrange(p5,p6,ncol=1)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
con1 <- data %>% 
  ggplot(aes(x=Air_temperature,y=Process_temperature))+
  geom_smooth()+
  geom_point(alpha=0.05)+
  labs(title = "Process teperature relative to air temperature",
       x="Process temperature [K]",
       y="Air temperature [K]")+
  theme_minimal(base_size = 25)+
  theme(axis.line = element_line(colour = "black"))

con2 <- data %>% 
  ggplot(aes(x=Rotational_speed,y=Torque))+
  geom_smooth(se=F)+
  geom_point(alpha=0.05)+
  labs(title = "Torque relative to rotational speed",
       x="Rotational speed [rpm]",
       y="Torque [Nm]")+
  theme_minimal(base_size = 25)+
  theme(axis.line = element_line(colour = "black"))

save(con1,con2,file = "plots/eda_con.rda")
```

```{r}
model.matrix(~0+., data=model_data[,c(9:14)]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
```

```{r}
model.matrix(~0+., data=model_data[,c(3:9)]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
```

```{r}
model.matrix(~0+., data=model_data[,-c(1:2)]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
```
